version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 5
    groups:
      python-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - playwright
          - pydantic-settings
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
